name: Test

on:
  #push:
  #  branches:
  #    - master

  #pull_request:

  workflow_dispatch:
    inputs:
      tags:
        description: "Tag Name"
        required: false

  workflow_call:

jobs:
  test:
    name: test
    #strategy:
    #  matrix:
    #    os: [macos-latest, ubuntu-latest, windows-latest]
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Build Grammar from yaml to json
        run: npm run bg

      - name: Test Grammar
        run: npm run testg

      #- name: Headless Test for the Web Extension
      #  run: xvfb-run -a npm test
